In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from SGDRegression import *
from BatchRegression import *
from MiniBatchRegression import *
from NormalRegression import *

from sklearn.model_selection import train_test_split

In [2]:

data = pd.read_csv('diamonds-train.csv')
columns = ['carat','cut','color','clarity','x','y','z','depth','table','price']
df = pd.DataFrame(data=data, columns=columns)
X = df[['carat','cut','color','clarity','x','y','z','depth','table']]
Y = df['price']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [3]:
xtreino3 = X_train[['x','y','z']]
xteste3 = X_test[['x','y','z']]

print(xtreino3.shape)
print(y_train.shape)
print(xteste3.shape)

(36679, 3)
(36679,)
(9170, 3)


In [4]:

clf = SGDRegression(1, 0.0001)
clf.fit(xtreino3, y_train)
print(clf.coef) #eq normal [-14097.24845234   2664.28448903    204.45318944    446.90189322]
clf.erroHistorico

[-1717.73661326   474.86980751   426.69199866   222.30262159]


[9088322.553410156]

In [5]:
clf.predict(xteste3)

array([3078.99750903, 5079.94590519, 4915.82456816, ..., 3674.66466223,
       5518.38208814, 4861.53945264])

In [6]:
from sklearn.linear_model import SGDRegressor
regr = SGDRegressor(max_iter=1000, eta0=0.0001)
regr.fit(xtreino3, y_train)
regr.coef_

array([2115.56597078,  353.99353355,  696.9710783 ])